### PR TITLE
Ratelimit meew0.

### PR DESCRIPTION
**Pull request by george99g**
My finger (read: macro) could handle the 99999 presses, but my browser couldn't.
clicks
death

### CODE REVIEW

**Comment by fennekid** [comment]
> devs click merge

Error Code 427: You are being rate limited

**Comment by deansheather** [comment]
Needs to be rate limiting, not blocking the feature completely.

**Comment by george99g** [comment]
Is this what you had in mind?

**Comment by deansheather** [comment]
Eh, it's a bit better I suppose. @SteamingMutt you have any opinions on this?

**Comment by Dougley** [comment]
I think the site should ask the user for confirmation if he wants to exceed the 1000, hardlimiting it seems a bit too much.

**Comment by deansheather** [comment]
Eh, you're right I suppose. Any chance you could change this to use an alert when the user crosses a large threshold, @george99g?

**Comment by george99g** [comment]
Something like this?

**Comment by Dougley** [comment]
👍

**Comment by deansheather** [comment]
I've simplified this in a branch on this repo, and have made a pull request for this: #4.

**Pull request closed without merging**
