### PR TITLE
Added hover text for keyboard shortcuts.

### PR DESCRIPTION
**Pull request by Zeludon**
For the people that don't stalk the github readme.

### CODE REVIEW

**Comment by deansheather** [comment]
Could you change the text to `( type _ )` please?

I.e. for the meew0 mode button, could the hover text say `( type m )`? I think this looks a bit nicer and gives a bit of context for the action.

**Comment by Roadcrosser** [comment]
I think `Press _` would sound better than `Type _`

**Comment by Zeludon** [comment]
Agreed, http://zeludon.me/takeb1nzyto.space/

Do you think it would look better with a full stop and a capital letter? `Press M.`

**Comment by Roadcrosser** [comment]
Capital letter yes, period, probably not.

**Comment by deansheather** [comment]
Eh, capital letters aren't necessary. I think people would assume that you need to click `SHIFT` too. In fact, `SHIFT` + `any key` won't fire any events. I'm going to merge as is.

**Pull request merged**
