### PR TITLE
Add a Dank Counter

### PR DESCRIPTION
**Pull request by indiv0**
I think this would be a fairly dank addition, and a useful way to count the number of dank for the project.

### CODE REVIEW

**Comment by indiv0** [comment]
I couldn't figure out how to center the div on the page, so it's a bit off to the right now (because it doesn't account for the text in the div). My CSS/JS is a bit rusty, so if you could let me know how to fix that (and any other issues you see), that'd be great!

**Comment by indiv0** [comment]
Additionally, I was thinking of making the number shake with a higher level of dank, progressively more and more violently.

**Comment by deansheather** [comment]
I don't understand the idea behind this, could you please explain why it would be useful?

**Comment by indiv0** [comment]
Also, whoops I just left in some commented code. I'll fix that right now.

**Comment by indiv0** [comment]
There's not much to understand, really. I saw your project and in the README it says: "Please make sure that your features are dank. Non-dank features will be declined.". So I thought of something I could contribute and I couldn't think of anything more dank than a literal dankness counter.

**Comment by indiv0** [comment]
If you don't think this feature is beneficial enough to be incorporated into the project, I understand.

**Comment by Dougley** [comment]
Hehe, this is funny, but it would be useful if this actually did something

**Comment by deansheather** [comment]
Any ideas for anything this could possibly do?

**Comment by Dougley** [comment]
Eeeh, not really

**Comment by deansheather** [comment]
I think if this had a cool idea behind it, rather than just being a counter, it would be a pretty cool addition to the site. Something like achievements, other celestial bodies added to the renderer pool, secret levels or something else that would be fun and make the users enjoy the site would be a cool addition.

If you could integrate something similar to that into this dank counter, that would be pretty cool in my opinion, and I'd probably merge this request.

**Comment by indiv0** [comment]
Hmm interesting idea. Any ideas for achievements or any other concrete things you want to see added?

**Comment by deansheather** [comment]
No idea, really. I think achievements would be pretty cool to be honest. Or even some kind of global leaderboard.

**Comment by Roadcrosser** [comment]
A global leaderboard would mean keeping a database and moving away from GitHub Pages.

**Comment by indiv0** [comment]
Technically you could stay on GitHub Pages, but just host a database elsewhere.
But yeah, that's mountains of additional complexity (preventing cheating, making a server-side portion for the app to provide an API, etc).

**Comment by deansheather** [comment]
Sorry for the late reply, only checked here today for something b1nzy wanted to add. Firebase would work as a database, right? I've never used Firebase before, but it looks good.

Also the leaderboard should apply to the meew0 counter, I don't think multiple counters are necessary (i.e. remove this counter).

**Comment by Dougley** [comment]
Firebase is a great solution, we can even host the site on there if we wanted to

**Comment by indiv0** [comment]
My only question is how to prevent cheating? Track connection duration server-side and ensure that users don't tamper with the meew0 counter locally?

**Comment by Roadcrosser** [comment]
Cheating is also another issue I had on my mind. Perhaps we should ratelimit the amount of meews that can happen a second?

**Comment by deansheather** [comment]
I feel like users will hate us for not letting them tamper with meew0 mode. People make scripts to increment meew0 mode for their screenshots.

The only problem with leaving it open for tampering is this cheating issue...

**Comment by deansheather** [comment]
I'm going to move this to an issue, this thread is pretty long and isn't on topic for the whole "Dank Counter" topic for this PR.

**Comment by deansheather** [comment]
This conversation has been moved to #13.

**Pull request closed without merging**
