### PR TITLE
 Responsive layout for smaller devices fixed #15

### LINKED ISSUE #15: Responsive layout for smaller devices
Currently, the site layout and styling doesn't work on smaller viewports.

### PR DESCRIPTION
**Pull request by hmelenok**
awesomescreenshot-2017-10-17t08-43-25-487z 1 1

### CODE REVIEW

**Review by Dougley — COMMENTED** [review]
LGTM, should be based on master though.

**Comment by Dougley** [comment]
@hmelenok Could you base this on master instead of on gh-pages? We'd prefer the source files being edited over the compiled version.

**Comment by deansheather** [comment]
@Dougley they did edit the source, this repository still has a master branch.

@hmelenok looks good to me, why has the src css file been beautified though? The indents in that file should be 2 spaces, not 4 spaces. Also, the cssshake section at the bottom of the file shouldn't be expanded.

**Review by deansheather — CHANGES_REQUESTED** [review]
See comment.

**Comment by hmelenok** [comment]
I”ll fix now

**Comment by hmelenok** [comment]
Don't actually see any master branch

**Comment by hmelenok** [comment]
@Dougley Please check it

**Comment by Dougley** [comment]
I was confused with another project, since we only have the gh-pages branch continue editing that.

**Review by Dougley — APPROVED** [review]

**Review by deansheather — APPROVED** [review]

**Pull request merged**
